### ISSUE TITLE
Case sensitive assert statements

### ISSUE THREAD

**Issue by jose** [antonio-mastropaolo/T5-learning-ICSE_2021#3]
Hi,

First of all thanks for sharing the data/scripts used in your ICSE publication.

I've successfully managed to generate an assert statement for a given test method, but the assert isn't case sensitive.  For instance, one of the generated asserts was:
```
org . junit . assert . asserttrue ( entry1 . equals ( entry2 ) )
```

which it won't compile when appended to a test method.
- `assert` should be [`Assert`](https://junit.org/junit4/javadoc/4.13/org/junit/Assert.html)
- `asserttrue` should be [`assertTrue`](https://junit.org/junit4/javadoc/4.13/org/junit/Assert.html#assertTrue(boolean)). 

That is,
```
org . junit . Assert . assertTrue ( entry1 . equals ( entry2 ) )
```

Is there any option/flag/parameter to force your model to generate case sensitive assert statements?

--
Best,
Jose

**Comment by antonio-mastropaolo** [comment]
Hello Jose,

Yep in this work, all the tokens have been lower-cased.
Nonetheless, this has been addressed in a follow-up study you can find here:

 -- Paper: https://arxiv.org/abs/2206.08574
 -- Replication Package: https://github.com/antonio-mastropaolo/TransferLearning4Code
